### ISSUE TITLE
R CMD check C/C++ pragma NOTE

### ISSUE THREAD

**Issue by trevorld** [jefferis/readobj#13]
Merging #8 (a newer version of ``tinyobjloader``) leads to the following R CMD note

```
❯ checking pragmas in C/C++ headers and code ... NOTE
  File which contains pragma(s) suppressing diagnostics:
    ‘src/tiny_obj_loader.h’
```

@jefferis commented in that PR that

> I'm afraid the second note will need an explanation and it's not guaranteed that CRAN will accept.
>
> See xtensor-stack/Xtensor.R#11 for an example. I think this means at a minimum that we need to figure out what compiler a warning is being suppressed by turning off the #pragma.

Note that @tylermorganwall also embeds a recent version of ``tinyobjloader`` in both ``{rayrender}`` and ``{rayvertex}`` and I don't see such a NOTE in his R CMD check results so he may have already figured out a workaround:

* https://cran.r-project.org/web/checks/check_results_rayrender.html
* https://cran.r-project.org/web/checks/check_results_rayvertex.html

**Comment by jefferis** [comment]
Good point re rayrender. This is the commit where he fixed that

https://github.com/tylermorganwall/rayrender/commit/6dc98d720b5f490c0a2450115348bfad62974927

**Comment by trevorld** [comment]
* @jefferis  I checked the code with rhub's Debian clang devel platform and everything seemed to check fine
* Everything also seems to work well locally including drawing textured shapes in rgl that ``rgl::readOBJ()`` chokes on
